#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CDK_DIR="${SCRIPT_DIR}/packages/synapse-cdk"
DEPLOY_CONFIG="${SCRIPT_DIR}/default_deploy.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }

# ──────────────────────────────────────────────
# Check prerequisites
# ──────────────────────────────────────────────
check_prerequisites() {
  local missing=0
  for cmd in aws node pnpm; do
    if ! command -v "$cmd" &>/dev/null; then
      error "$cmd is not installed"
      missing=1
    fi
  done
  if [ "$missing" -eq 1 ]; then
    exit 1
  fi

  # Check AWS credentials
  if ! aws sts get-caller-identity &>/dev/null; then
    error "AWS credentials not configured. Run 'aws configure' or set AWS_PROFILE."
    exit 1
  fi

  local account_id region
  account_id=$(aws sts get-caller-identity --query Account --output text)
  region=$(aws configure get region 2>/dev/null || echo "us-east-1")
  info "AWS Account: ${account_id}, Region: ${region}"
}

# ──────────────────────────────────────────────
# Collect configuration interactively
# ──────────────────────────────────────────────
collect_config() {
  echo ""
  echo -e "${CYAN}═══════════════════════════════════════════${NC}"
  echo -e "${CYAN}  Synapse CDK Deployment Configuration${NC}"
  echo -e "${CYAN}═══════════════════════════════════════════${NC}"
  echo ""

  # Stack name
  read -rp "Stack name [Synapse]: " STACK_NAME
  STACK_NAME="${STACK_NAME:-Synapse}"

  # ACM Certificate ARN (required)
  while true; do
    read -rp "ACM Certificate ARN (required): " ACM_CERT_ARN
    if [[ "$ACM_CERT_ARN" == arn:aws:acm:* ]]; then
      break
    fi
    warn "Must be a valid ACM certificate ARN (arn:aws:acm:...)"
  done

  # Custom domain (optional)
  read -rp "Custom domain (optional, e.g. synapse.example.com): " CUSTOM_DOMAIN

  # Super admin email (required)
  while true; do
    read -rp "Super admin email (required): " ADMIN_EMAIL
    if [[ "$ADMIN_EMAIL" == *@* ]]; then
      break
    fi
    warn "Please enter a valid email address."
  done

  # Super admin password (required)
  while true; do
    read -rsp "Super admin password (required, min 8 chars): " ADMIN_PASSWORD
    echo ""
    if [ "${#ADMIN_PASSWORD}" -ge 8 ]; then
      break
    fi
    warn "Password must be at least 8 characters."
  done

  # NextAuth secret (optional)
  read -rp "NextAuth secret (leave empty to auto-generate): " NEXTAUTH_SECRET
}

# ──────────────────────────────────────────────
# Build CDK context arguments
# ──────────────────────────────────────────────
build_context_args() {
  CDK_CONTEXT="-c stackName=${STACK_NAME}"
  CDK_CONTEXT+=" -c acmCertificateArn=${ACM_CERT_ARN}"
  CDK_CONTEXT+=" -c superAdminEmail=${ADMIN_EMAIL}"
  CDK_CONTEXT+=" -c superAdminPassword=${ADMIN_PASSWORD}"

  if [ -n "${CUSTOM_DOMAIN:-}" ]; then
    CDK_CONTEXT+=" -c customDomain=${CUSTOM_DOMAIN}"
  fi
  if [ -n "${NEXTAUTH_SECRET:-}" ]; then
    CDK_CONTEXT+=" -c nextAuthSecret=${NEXTAUTH_SECRET}"
  fi
}

# ──────────────────────────────────────────────
# Save deployment config for re-runs
# ──────────────────────────────────────────────
save_deploy_config() {
  cat > "$DEPLOY_CONFIG" <<DEPLOY_EOF
#!/usr/bin/env bash
# Auto-generated by install.sh — DO NOT commit this file
set -euo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
CDK_DIR="\${SCRIPT_DIR}/packages/synapse-cdk"

STACK_NAME="${STACK_NAME}"
ACM_CERT_ARN="${ACM_CERT_ARN}"
CUSTOM_DOMAIN="${CUSTOM_DOMAIN:-}"
ADMIN_EMAIL="${ADMIN_EMAIL}"
ADMIN_PASSWORD="${ADMIN_PASSWORD}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-}"

CDK_CONTEXT="-c stackName=\${STACK_NAME}"
CDK_CONTEXT+=" -c acmCertificateArn=\${ACM_CERT_ARN}"
CDK_CONTEXT+=" -c superAdminEmail=\${ADMIN_EMAIL}"
CDK_CONTEXT+=" -c superAdminPassword=\${ADMIN_PASSWORD}"
[ -n "\${CUSTOM_DOMAIN}" ] && CDK_CONTEXT+=" -c customDomain=\${CUSTOM_DOMAIN}"
[ -n "\${NEXTAUTH_SECRET}" ] && CDK_CONTEXT+=" -c nextAuthSecret=\${NEXTAUTH_SECRET}"

cd "\${SCRIPT_DIR}"
pnpm -C packages/synapse-cdk install
pnpm -C packages/synapse-cdk run build
pnpm -C packages/synapse-cdk exec cdk bootstrap \${CDK_CONTEXT}
pnpm -C packages/synapse-cdk exec cdk deploy \${CDK_CONTEXT} --require-approval never
DEPLOY_EOF
  chmod +x "$DEPLOY_CONFIG"
  ok "Saved deployment config to default_deploy.sh (re-run with ./default_deploy.sh)"
}

# ──────────────────────────────────────────────
# Deploy
# ──────────────────────────────────────────────
deploy() {
  info "Installing dependencies..."
  pnpm -C packages/synapse-cdk install

  info "Building CDK..."
  pnpm -C packages/synapse-cdk run build

  info "Bootstrapping CDK..."
  pnpm -C packages/synapse-cdk exec cdk bootstrap ${CDK_CONTEXT}

  info "Deploying stack '${STACK_NAME}'..."
  pnpm -C packages/synapse-cdk exec cdk deploy ${CDK_CONTEXT} --require-approval never

  ok "Deployment complete!"
}

# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────
main() {
  cd "$SCRIPT_DIR"

  echo -e "${GREEN}"
  echo "  ╔═══════════════════════════════════╗"
  echo "  ║       Synapse CDK Installer        ║"
  echo "  ╚═══════════════════════════════════╝"
  echo -e "${NC}"

  # Reuse existing config?
  if [ -f "$DEPLOY_CONFIG" ]; then
    warn "Found existing deployment config: default_deploy.sh"
    read -rp "Reuse previous configuration? [Y/n]: " reuse
    if [[ "${reuse:-Y}" =~ ^[Yy]$ ]]; then
      info "Re-running previous deployment..."
      exec "$DEPLOY_CONFIG"
    fi
  fi

  check_prerequisites
  collect_config
  build_context_args
  save_deploy_config
  deploy
}

main "$@"
